# https://ticketing.dev/api/users/currentuser 

# POST https://ticketing.dev/api/users/signup
# content-type: application/json

# {
#   "email": "test@test.com",
#   "password": "password"
# }

# POST https://ticketing.dev/api/users/signin
# content-type: application/json

# {
#   "email": "test@test.com",
#   "password": "password"
# }

# POST https://ticketing.dev/api/tickets
# content-type: application/json

# {
#   "title": "Friends",
#   "price": 60
# }

# https://ticketing.dev/api/tickets/5fd8442eaa73f90019dc8832

# https://ticketing.dev/api/tickets/

# PUT https://ticketing.dev/api/tickets/60029252cba1360018999688
# content-type: application/json

# {
#   "title": "One Piece",
#   "price": 40
# }

# POST https://ticketing.dev/api/orders
# content-type: application/json

# {
#   "ticketId": "6003d62296aa6f0018f93100"
# }

POST https://ticketing.dev/api/payments
content-type: application/json

{}